Install composer for circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,6 +3,25 @@
 # Check https://circleci.com/docs/2.0/language-php/ for more details
 #
 version: 2
+
+install_composer: &install_composer
+    command: |
+        cd /tmp
+        EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
+        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+        ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+        then
+            >&2 echo 'ERROR: Invalid installer signature'
+            rm composer-setup.php
+            exit 1
+        fi
+
+        sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
+        RESULT=$?
+        rm composer-setup.php
+        exit $RESULT
+
 jobs:
   build:
     docker:
@@ -18,6 +37,9 @@ jobs:
 
     steps:
       - checkout
+
+      - run:
+          <<: *install_composer
 
       # Download and cache dependencies
       - restore_cache:
